apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor
  namespace: harbor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: harbor
  endpoints:
  - port: metrics