apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - image: "{{ .Values.WORKER.IMAGE }}:{{ .Values.WORKER.TAG }}"
          imagePullPolicy: Always
          name: worker
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: REDIS_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: worker-db-secret
                  key: DB_HOST
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "1280Mi"
              cpu: "1000m"
