apiVersion: v1
kind: Secret
metadata:
  name: yamltoinfra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devops-advanced-camp/code.git
  password: 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
  username: lyzhang1999
  insecure: "true"
  forceHttpBasicAuth: "true"
  enableLfs: "true"
