apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: run-git-clone
spec:
  # 在安装 jenkins 时已经提前部署了 serviceaccount
  serviceAccountName: build-bot
  taskRef:
    name: git-clone
  params:
    - name: url
      value: "https://github.com/devops-advanced-camp/vote.git"
  workspaces:
    - emptyDir: {}
      name: output
