apiVersion: v1
kind: Secret
metadata:
  name: sonar-user-pass
type: Opaque
stringData:
  login: "squ_bbc66aaf3502aff6a1abee2e56837d0ff5b432d8"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonar-user-pass
secrets:
  - name: sonar-user-pass
