apiVersion: v1
kind: Secret
metadata:
  name: "gitlab-pull-secret"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: root
  password: glpat-W1EnrRBixH8RuqDzezmR