apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-kubeconfig
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-kubeconfig
roleRef:
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: jenkins-kubeconfig
    namespace: jenkins
