apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: git_url
    - name: commit_id
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: github-run-
      spec:
        taskRunSpecs:
          - pipelineTaskName: git-clone
            serviceAccountName: build-bot
        pipelineRef:
          name: github-pipeline
        workspaces:
          - name: output
            persistentVolumeClaim:
              claimName: pipeline-pvc
            subPath: $(context.pipelineRun.uid)
          - name: sonar-credentials
            secret:
              secretName: sonar-user-pass
          - name: docker-credentials
            secret:
              secretName: docker-credentials
        params:
          - name: git_url
            value: $(tt.params.git_url) # 注意：$tt 开头，从 EventListener binding params 获取
          - name: microservice
            value: "result"
          - name: git_repository
            value: "vote"
          - name: commit_id
            value: $(tt.params.commit_id)
          - name: registry_url
            value: "harbor.wangwei.devopscamp.us"
