apiVersion: v1  
kind: Secret  
metadata:  
  name: harbor-pull-secret
type: kubernetes.io/dockerconfigjson  
data:  
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.imageRegistry.server .Values.imageRegistry.username .Values.imageRegistry.password | b64enc | quote }}  
