apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - image: "{{ .Values.VOTE.IMAGE }}:{{ .Values.VOTE.TAG }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "1280Mi"
              cpu: "1000m"
          # add readiness and liveness probes
          readinessProbe:
            httpGet:
              port: 80
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 80
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: vote-configmap
          name: vote
          ports:
            - containerPort: 80
              name: vote