# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "tencentcloud" {
    region = "ap-guangzhou"
    secret_id = "AKIDrY2IL9j4BnCNJ1VklaCaicaKp57wXt2z"
    secret_key = "nNm02sVyW3PYZP3VlqjPtPq6C8tRo492"
}
