apiVersion: v1
kind: Secret
metadata:
  name: "github-pull-secret"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: lyzhang1999
  password: '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'