apiVersion: v1
kind: Secret
metadata:
  name: "sonarqube-token"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description": "credentials from Kubernetes of Sonarqube"
type: Opaque
stringData:
  text: "squ_bbc66aaf3502aff6a1abee2e56837d0ff5b432d8"
