# syntax=docker/dockerfile:1
FROM golang:1.21.1-alpine3.18 as builder
WORKDIR /opt/app
COPY . .
RUN go mod tidy && go build -o example


FROM alpine:latest
WORKDIR /opt/app
COPY --from=builder /opt/app/example ./example
CMD ["/opt/app/example"]